// Generated by CoffeeScript 1.6.3
(function() {
  var reg;

  reg = /\{(.*?)\}/g;

  $(function() {
    return $('.js-card-name').each(function() {
      var tags;
      tags = $(this).html().replace(reg, '<span class="tt-tag">$1</span>');
      return $(this).html(tags);
    });
  });

}).call(this);
